# Generated by Django 3.2.25 on 2025-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='unique_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
