# Generated by Django 3.2.25 on 2025-02-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
