# Generated by Django 3.2.25 on 2025-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Finance Officer', 'Finance Officer'), ('Marketing Officer', 'Marketing Officer'), ('normal user', 'normal user')], max_length=200, null=True),
        ),
    ]
