# Generated by Django 3.2.25 on 2025-02-28 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_staff_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='First_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='Last_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
